#pragma once

enum ExplosionState {
    EXPLOSION_CENTER,
    EXPLOSION_UP,
    EXPLOSION_DOWN,
    EXPLOSION_LEFT,
    EXPLOSION_RIGHT,
    EXPLOSION_UP_END,
    EXPLOSION_DOWN_END,
    EXPLOSION_LEFT_END,
    EXPLOSION_RIGHT_END,
};
